./plotBHMassLimits.py -i XsecLimits.root -m BH2_CH
./plotBHMassLimits.py -i XsecLimits.root -m BH4_CH
./plotBHMassLimits.py -i XsecLimits.root -m BH6_CH
./plotBHMassLimits.py -i XsecLimits.root -m BH8_CH
./plotBHMassLimits.py -i XsecLimits.root -m BH9_CH
./plotBHMassLimits.py -i XsecLimits.root -m BH10_CH
./plotBHMassLimits.py -i XsecLimits.root -m BH1_BM
./plotBHMassLimits.py -i XsecLimits.root -m BH2_BM
./plotBHMassLimits.py -i XsecLimits.root -m BH5_BM
